name: flutter_galeriya
description: A simple gallery app built with Flutter.

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^0.8.4+4
  image_picker_for_web: ^2.1.7
  path_provider: ^2.0.5
  flutter_staggered_grid_view: ^0.4.0
  cached_network_image: ^3.0.0
  carousel_slider: ^4.0.0
  provider: ^6.0.0
  video_player: ^2.2.12


dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
